# Generated by Django 4.2 on 2023-04-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_password_user_passwor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwor',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
