# Generated by Django 4.2 on 2023-04-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_todolistview_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
